#!/usr/bin/env python3
"""
Generate clock overlay fonts at multiple point sizes for tile-aware scaling.

The build runs this through scripts/extra/gen_dseg_font.py, so the headers are
generated artifacts and are not committed. The committed source is the TTF in
third_party/fonts/: DSEG7 Modern Bold Italic by keshikan, SIL OFL 1.1, bundled
under clause 2 with third_party/fonts/DSEG-LICENSE.txt.

Run it by hand only to preview a font or size change.

Outputs include/fonts/dseg_<pt>.h and include/fonts/dseg_fonts.h.

Requires freetype2. Builds FastEPD fontconvert on first run.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INCLUDE = ROOT / "include/fonts"
FONT_DIR = ROOT / "third_party/fonts"
TTF_NAMES = ("DSEG7Modern-BoldItalic.ttf",)
MANIFEST_H = INCLUDE / "dseg_fonts.h"
FIRST_CHAR = 48  # '0'
LAST_CHAR = 58   # ':'

DEFAULT_SIZES = "120,140,160,200,240,280,320,380,460,560,680"

CREDIT = (
    "// Generated from DSEG7 Modern Bold Italic by keshikan (http://www.keshikan.net).\n"
    "// Copyright (c) 2017, keshikan, with Reserved Font Name \"DSEG\".\n"
    "// Licensed under the SIL Open Font License 1.1 - see\n"
    "// third_party/fonts/DSEG-LICENSE.txt. Generated at build time - do not commit.\n"
)


def parse_sizes() -> list[int]:
    raw = os.environ.get("CLOCK_FONT_SIZES", DEFAULT_SIZES)
    sizes = sorted({int(x.strip()) for x in raw.split(",") if x.strip()})
    sizes = [s for s in sizes if s >= 60]
    if not sizes:
        raise SystemExit("CLOCK_FONT_SIZES must list at least one size >= 60")
    return sizes


def find_ttf() -> Path | None:
    override = os.environ.get("CLOCK_FONT_TTF")
    if override:
        path = Path(override)
        return path if path.is_file() else None
    for name in TTF_NAMES:
        path = FONT_DIR / name
        if path.is_file():
            return path
    return None


def find_fontconvert() -> Path:
    env = os.environ.get("PIOENV", "TRMNL_X_dev")
    libdeps = ROOT / ".pio/libdeps"
    candidates = [
        libdeps / env / "FastEPD/fontconvert/fontconvert",
        libdeps / "TRMNL_X_dev" / "FastEPD/fontconvert/fontconvert",
    ]
    for binary in candidates:
        if binary.is_file():
            return binary

    src_dir = libdeps / env / "FastEPD/fontconvert"
    if not (src_dir / "main.c").is_file():
        for alt in libdeps.glob("*/FastEPD/fontconvert/main.c"):
            src_dir = alt.parent
            break

    if not (src_dir / "main.c").is_file():
        raise SystemExit("FastEPD fontconvert not found. Run: pio run -e TRMNL_X_dev (installs libdeps)")

    subprocess.run(["make", "-C", str(src_dir)], check=True)
    binary = src_dir / "fontconvert"
    if not binary.is_file():
        raise SystemExit(f"fontconvert build failed in {src_dir}")
    return binary


def generate_one(fontconvert: Path, ttf: Path, pt: int) -> Path:
    out_h = INCLUDE / f"dseg_{pt}.h"
    cmd = [str(fontconvert), str(ttf), str(out_h), str(pt), str(FIRST_CHAR), str(LAST_CHAR)]
    print(f"Running: {' '.join(cmd)}")
    subprocess.run(cmd, check=True)
    text = out_h.read_text()
    text = text.replace(f"dseg_{pt}.tmp", f"dseg_{pt}")
    out_h.write_text(CREDIT + text)
    return out_h


def write_manifest(sizes: list[int]) -> None:
    lines = [
        "// Auto-generated by scripts/gen_dseg_font.py - do not edit.",
        CREDIT.rstrip("\n"),
        "#ifndef DSEG_FONTS_H",
        "#define DSEG_FONTS_H",
        "",
    ]
    for pt in sizes:
        lines.append(f'#include "dseg_{pt}.h"')
    lines.append("")
    lines.append(f"#define DSEG_FONT_COUNT {len(sizes)}")
    lines.append("")
    lines.append("// Largest first: clock_pick_dseg_font() takes the first that fits the tile.")
    lines.append("static const void *dseg_fonts[DSEG_FONT_COUNT] = {")
    for pt in reversed(sizes):
        lines.append(f"  dseg_{pt},")
    lines.append("};")
    lines.append("")
    lines.append("static const int dseg_font_pt[DSEG_FONT_COUNT] = {")
    for pt in reversed(sizes):
        lines.append(f"  {pt},")
    lines.append("};")
    lines.append("")
    lines.append("#endif")
    MANIFEST_H.write_text("\n".join(lines) + "\n")
    print(f"Wrote {MANIFEST_H}")


def main() -> int:
    ttf = find_ttf()
    if not ttf:
        print(f"Clock font TTF not found. Place one of {TTF_NAMES} in third_party/fonts/")
        return 1

    sizes = parse_sizes()
    fontconvert = find_fontconvert()
    INCLUDE.mkdir(parents=True, exist_ok=True)

    for pt in sizes:
        out = generate_one(fontconvert, ttf, pt)
        print(f"Wrote {out} ({out.stat().st_size} bytes)")

    write_manifest(sizes)
    return 0


if __name__ == "__main__":
    sys.exit(main())
