// ============================================================
// AUTO-GENERATED by scripts/generate_branding.py - DO NOT EDIT
// Edit config.yml and re-run the generator instead.
// ============================================================
#ifndef BRANDING_H
#define BRANDING_H

// --- Core identity ---
#define BRAND_DEVICE_NAME  "TRMNL"

// --- URLs ---
#define BRAND_API_BASE_URL "https://trmnl.app"
#define BRAND_SETUP_URL    "trmnl.com/start"

// --- User-facing strings ---
#define BRAND_STR_OTG_ON                         "OTG turned on!"
#define BRAND_STR_OTG_OFF                        "OTG turned off!"
#define BRAND_STR_MODEM_FLASHING                 "Flashing modem firmware..."
#define BRAND_STR_MODEM_FLASH_FAILED_1           "Failed to flash modem firmware,"
#define BRAND_STR_MODEM_FLASH_FAILED_2           "device would only operate with 2.4Ghz WiFi."
#define BRAND_STR_READY_TO_SHIP                  "Device is ready to ship!"
#define BRAND_STR_UNPLUG_USB                     "Unplug the USB-C to enter shipping mode."
#define BRAND_STR_WELCOME                        "Welcome to TRMNL."
#define BRAND_STR_DOCK_INSTRUCTIONS              "Attach the dock and a USB-C to get started."
#define BRAND_STR_WIFI_RESET_CONFIRM             "Are you sure you want to reset WiFi settings?"
#define BRAND_STR_POWER_OFF_CONFIRM              "Turn off device?"
#define BRAND_STR_CONFIRM_INSTRUCTIONS           "Hold middle of touch bar to confirm, tap to cancel."
#define BRAND_STR_WIFI_CONNECT_SHORT             "Connect to TRMNL WiFi"
#define BRAND_STR_WIFI_CONNECT_SUBTITLE          "on your phone or computer"
#define BRAND_STR_WIFI_FAILED                    "Can't establish WiFi connection."
#define BRAND_STR_WIFI_FAILED_HELP_BUTTON        "Hold button on the back to reset WiFi, or scan QR Code for help."
#define BRAND_STR_WIFI_FAILED_HELP_TOUCHBAR      "Hold left and right corner of touch bar to reset WiFi, or scan QR Code for help."
#define BRAND_STR_API_INTERNAL_ERROR_1           "WiFi connected, but"
#define BRAND_STR_API_INTERNAL_ERROR_2           "API connection cannot be"
#define BRAND_STR_API_INTERNAL_ERROR_3           "established. Try to refresh,"
#define BRAND_STR_API_INTERNAL_ERROR_4           "or scan QR Code for help."
#define BRAND_STR_WIFI_WEAK                      "WiFi connected but signal is weak"
#define BRAND_STR_API_REQUEST_FAILED             "WiFi connected, request to API failed."
#define BRAND_STR_API_UNABLE_TO_CONNECT          "WiFi connected, unable connect to API."
#define BRAND_STR_API_SETUP_FAILED               "WiFi connected, /api/setup returned error."
#define BRAND_STR_API_SIZE_ERROR                 "WiFi connected, TRMNL content malformed."
#define BRAND_STR_API_FIRMWARE_UPDATE_ERROR      "WiFi connected, could not get firmware update from api."
#define BRAND_STR_API_IMAGE_DOWNLOAD_ERROR       "WiFi connected, API could not deliver image to device."
#define BRAND_STR_IMAGE_TIMEOUT                  "Image download timed out; check your network status."
#define BRAND_STR_TAP_BUTTON                     "Short click the button on back,"
#define BRAND_STR_TAP_TOUCHBAR                   "Tap the middle of touch bar,"
#define BRAND_STR_CHECK_INTERNET                 "otherwise check your internet."
#define BRAND_STR_HOLD_BUTTON_RESET              "Wait or reset by holding button on back."
#define BRAND_STR_HOLD_TOUCHBAR_RESET            "Wait or reset by holding left and right corner of touch bar."
#define BRAND_STR_FW_UPDATE_AVAILABLE            "Firmware update available! Starting now..."
#define BRAND_STR_FW_UPDATE_FAILED               "Firmware update failed. Device will restart..."
#define BRAND_STR_FW_UPDATE_SUCCESS              "Firmware update success. Device will restart..."
#define BRAND_STR_QA_STARTING                    "Starting QA test"
#define BRAND_STR_IMAGE_TOO_LARGE                "The image file from this URL is too large."
#define BRAND_STR_PNG_MAX_PREFIX                 "PNG images can be a maximum of"
#define BRAND_STR_IMAGE_FORMAT_INCORRECT         "The image format is incorrect"
#define BRAND_STR_WIFI_RETRY_LIMIT               "Maximum WiFi retries reached."
#define BRAND_STR_WIFI_RETRY_PRESS               "Press button to manually refresh."
#define BRAND_STR_WIFI_RETRY_HOLD                "Hold button to reset WiFi and try another network."
#define BRAND_STR_PORTAL_TIMEOUT                 "Wifi Captive Portal timed out"
#define BRAND_STR_TRY_AGAIN_TOUCHBAR             "Tap touchbar to try again"
#define BRAND_STR_TRY_AGAIN_BUTTON               "Press button to try again"
#define BRAND_STR_SETUP_VISIT                    "Please visit trmnl.com/start"
#define BRAND_STR_FRIENDLY_ID_PREFIX             "with Friendly ID "
#define BRAND_STR_FRIENDLY_ID_SUFFIX             " to finish setup"
#define BRAND_STR_FW_PREFIX                      "TRMNL firmware "
#define BRAND_STR_WIFI_CONNECT_MESSAGE_PREFIX    "Connect your phone or computer to "
#define BRAND_STR_WIFI_CONNECT_DEFAULT_NAME      "the TRMNL"
#define BRAND_STR_WIFI_CONNECT_MESSAGE_SUFFIX    " Wi-Fi"
#define BRAND_STR_SCAN_QR_HELP                   "or scan the QR code for help"

#endif  // BRANDING_H
